language: python

sudo: true

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - TEST_TYPE=test

cache:
  directories:
  - $HOME/.cache/pip

install:
  - make setup

script:
  - make ${TEST_TYPE}
